import Advertisement from '@/components/organism/advertisement/Advertisement'
import BannerCard from '@/components/molecules/card/BannerCard'
import PostCard from '@/components/molecules/card/PostCard'
import Link from 'next/link'

export const metadata = {
   title: 'Home Page | MetaBlog',
   description: 'Generated by create next app',
}
function secondPost() {
   return (
      <div className="card w-fit p-4 border border-base-content/10 rounded-xl font-work">
         <figure>
            <img
               src="https://incubator.ucf.edu/wp-content/uploads/2023/07/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg"
               alt="email"
               className={`rounded-xl`}
               width={360}
               height={240}
            />
         </figure>
         <div className="card-body py-6 px-2">
            <span className="btn no-animation hover:bg-primary hover:text-primary-content bg-primary/5 border-0 text-primary text-sm px-3 py-2 min-h-fit h-fit rounded-md w-fit capitalize font-medium">
               Technology
            </span>
            <h3>
               <Link
                  href="/second-post"
                  className="text-base-content hover:text-primary transition-all duration-300 ease-in-out font-semibold text-lg md:text-xl lg:text-2xl mt-2"
               >
                  AI: Shaping the Future of Technology
               </Link>
            </h3>
            <div className="mt-5 flex items-center gap-5 text-base-content/60 ">
               <div className=" flex items-center gap-3">
                  <div className="avatar">
                     <div className="w-9 rounded-full">
                        <img
                           src="https://avatars.githubusercontent.com/u/110733438?s=96&v=4"
                           alt="avatar"
                        />
                     </div>
                  </div>
                  <h5>
                     <Link
                        href="/author"
                        className="text-base font-medium hover:text-primary transition hover:duration-300"
                     >
                        Atharv Sankpal
                     </Link>
                  </h5>
               </div>
               <p className="text-base">March 22 2024</p>
            </div>
         </div>
      </div>
   )
}

function thirdPost() {
   return (
      <div className="card w-fit p-4 border border-base-content/10 rounded-xl font-work">
         <figure>
            <img
               src="https://puffy.com/cdn/shop/articles/how-to-meditate-3_1024x.jpg?v=1639635327"
               alt="email"
               className={`rounded-xl`}
               width={360}
               height={240}
            />
         </figure>
         <div className="card-body py-6 px-2">
            <span className="btn no-animation hover:bg-primary hover:text-primary-content bg-primary/5 border-0 text-primary text-sm px-3 py-2 min-h-fit h-fit rounded-md w-fit capitalize font-medium">
               Wellness
            </span>
            <h3>
               <Link
                  href="/third-post"
                  className="text-base-content hover:text-primary transition-all duration-300 ease-in-out font-semibold text-lg md:text-xl lg:text-2xl mt-2"
               >
                  Meditation: Calm your Mind and Reduce Stress
               </Link>
            </h3>
            <div className="mt-5 flex items-center gap-5 text-base-content/60 ">
               <div className=" flex items-center gap-3">
                  <div className="avatar">
                     <div className="w-9 rounded-full">
                        <img
                           src="https://avatars.githubusercontent.com/u/110733438?s=96&v=4"
                           alt="avatar"
                        />
                     </div>
                  </div>
                  <h5>
                     <Link
                        href="/author"
                        className="text-base font-medium hover:text-primary transition hover:duration-300"
                     >
                        Atharv Sankpal
                     </Link>
                  </h5>
               </div>
               <p className="text-base">March 22 2024</p>
            </div>
         </div>
      </div>
   )
}

export default function Home() {
   return (
      <main className="container mx-auto">
         {/* Banner Component */}
         <section>
            <BannerCard />
         </section>

         {/* Advertisement Component */}
         <section className="pt-12">
            <Advertisement />
         </section>

         {/* Latest Post */}
         <section className="my-20">
            <h3 className="text-base-content font-bold text-2xl mb-8 font-work leading-8">
               Latest Post
            </h3>

            <div className=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
               {secondPost()}
               {thirdPost()}
               {[2, 3, 4, 5, 6, 7, 8].map((item: any) => (
                  <PostCard key={item} />
               ))}
            </div>
            <div className="flex items-center justify-center w-full mt-8">
               <Link
                  href={`/blog`}
                  className="btn btn-outline btn-secondary text-secondary-content/60 font-work font-medium text-base"
               >
                  View All Post
               </Link>
            </div>
         </section>

         {/* Advertisement Component */}
         <section className="mb-24">
            <Advertisement />
         </section>
      </main>
   )
}
